IF OBJECT_ID('tbl_JewelleryProduct', 'U') IS NULL
BEGIN
    CREATE TABLE tbl_JewelleryProduct (
        JewelleryId INT IDENTITY(1,1) PRIMARY KEY,
        Title NVARCHAR(300) NOT NULL,
        ShortDescription NVARCHAR(1000) NULL,
        Description NVARCHAR(MAX) NULL,
        Image1 NVARCHAR(500) NULL,
        Image2 NVARCHAR(500) NULL,
        Image3 NVARCHAR(500) NULL,
        Image4 NVARCHAR(500) NULL,
        GoldWeight DECIMAL(18,3) NOT NULL DEFAULT 0,
        SilverWeight DECIMAL(18,3) NOT NULL DEFAULT 0,
        DiamondCarat DECIMAL(18,3) NOT NULL DEFAULT 0,
        MakingCharges DECIMAL(18,2) NOT NULL DEFAULT 0,
        GstPercent DECIMAL(5,2) NOT NULL DEFAULT 0,
        GoldRate DECIMAL(18,2) NOT NULL DEFAULT 0,
        SilverRate DECIMAL(18,2) NOT NULL DEFAULT 0,
        DiamondRate DECIMAL(18,2) NOT NULL DEFAULT 0,
        GoldAmount DECIMAL(18,2) NOT NULL DEFAULT 0,
        SilverAmount DECIMAL(18,2) NOT NULL DEFAULT 0,
        DiamondAmount DECIMAL(18,2) NOT NULL DEFAULT 0,
        Subtotal DECIMAL(18,2) NOT NULL DEFAULT 0,
        GstAmount DECIMAL(18,2) NOT NULL DEFAULT 0,
        Price DECIMAL(18,2) NOT NULL DEFAULT 0,
        MRP DECIMAL(18,2) NOT NULL DEFAULT 0,
        BV DECIMAL(18,2) NOT NULL DEFAULT 0,
        HSNCode NVARCHAR(50) NULL,
        MetalType NVARCHAR(50) NULL,
        JewelleryType NVARCHAR(100) NULL,
        SizeId INT NULL,
        SizeName NVARCHAR(100) NULL,
        Status BIT NOT NULL DEFAULT 1,
        CreatedOn DATETIME NOT NULL DEFAULT GETDATE(),
        CreatedBy NVARCHAR(100) NULL
    );
END
